name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: echo "GIT_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

      - name: Generate release notes
        run: echo "RELEASE_NOTES=$(git log -1 --pretty=format:%B)" >> $GITHUB_ENV

      - name: Escape folder name
        run: |
            echo "ZIP_FILE_NAME=$(echo ${{ vars.FOLDER_NAME }}-${{ env.GIT_TAG }}.zip | sed 's/ /_/g')" >> $GITHUB_ENV

      - run: git checkout ${{env.GIT_TAG}}

      - name: Create .zip
        run: |
          cp -r src "${{vars.FOLDER_NAME}}"
          cp README.md "${{vars.FOLDER_NAME}}"
          zip -r -q ${{env.ZIP_FILE_NAME}} "${{vars.FOLDER_NAME}}"


      - name: Upload to Blender Extensions
        run: |
          curl -X POST https://extensions.blender.org/api/v1/extensions/${{vars.EXTENSION_ID}}/versions/upload/ \
            -H "Authorization:bearer ${{secrets.API_KEY}}" \
            -F "version_file=@${{env.ZIP_FILE_NAME}}" \
            -F "release_notes=${{env.RELEASE_NOTES}}"

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: ${{env.RELEASE_NOTES}}
          artifacts: |
            ${{env.ZIP_FILE_NAME}}
          draft: false
          prerelease: false
