name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: echo "GIT_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

      - run: git checkout ${{env.GIT_TAG}}

      - name: Create .zip
        run: cd src/ && zip -r -q ../SMTH_Blender_Smart_Tools_${{env.GIT_TAG}}.zip .*

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: |
            SMTH_Blender_Smart_Tools_${{env.GIT_TAG}}.zip
          draft: false
          prerelease: false
