name: release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: echo "GIT_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

      - run: git checkout ${{env.GIT_TAG}}

      - name: Escape folder name
        run: |
          echo "UNDERSCORE_FOLDER_NAME=$(echo ${{ vars.FOLDER_NAME }} | sed 's/ /_/g')" >> $GITHUB_ENV

      - name: Create .zip
        run: |
          cp -r src "${{vars.FOLDER_NAME}}"
          cp README.md "${{vars.FOLDER_NAME}}"
          zip -r -q ${{env.UNDERSCORE_FOLDER_NAME}}.zip "${{vars.FOLDER_NAME}}"

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: |
            ${{env.UNDERSCORE_FOLDER_NAME}}.zip
          draft: false
          prerelease: false
